---
# roles/bin_setup/task/main.yml

# - name: Check if swapfile exists
#   stat:
#     path: /swapfile
#   register: swapfile_exists

# - name: Disable swap
#   become: true
#   ansible.builtin.command: swapoff /swapfile
#   ignore_errors: true

# - name: Debug swapfile status
#   debug:
#     var: swapfile_exists
  
# - name: Remove swapfile if exists
#   ansible.builtin.file:
#     path: /swapfile
#     state: absent
#   become: true

# - name: Create a new swap file
#   command: fallocate -l 1G /swapfile

# - name: Set the swap file permissions
#   file:
#     path: /swapfile
#     mode: '0600'

# - name: Format swap file
#   command: mkswap /swapfile

# - name: Enable the swap file
#   command: swapon /swapfile

- name: Run bin/setup script
  ansible.builtin.shell: >
    bash -lc 'eval "$(rbenv init -)"; bundle install'
  args:
    chdir: /home/ec2-user/raisetech-live8-sample-app
  environment:
    RBENV_ROOT: "{{ rbenv_root }}"
    PATH: "{{ rbenv_root }}/bin:{{ rbenv_root }}/shims:{{ ansible_env.PATH }}"
  become_user: ec2-user

