---
# roles/nodejs/tasks/main.yml

- name: Add NodeSource repository (Node.js 18 LTS)
  shell: curl -sL https://rpm.nodesource.com/setup_18.x | bash -

- name: Install Node.js
  ansible.builtin.shell: "sudo yum install -y nodejs"

