---
# roles/nodejs/tasks/main.yml

# - name: Add NodeSource repository
#   ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_14.x | bash -

# - name: Install Node.js
#   ansible.builtin.shell: "sudo yum install -y nodejs"

- name: Enable Amazon Linux Extras repository for Node.js 18
  shell: amazon-linux-extras enable nodejs18 && yum clean metadata
  args:
    warn: false  # シェルの警告を抑制

- name: Install Node.js 18
  yum:
    name: nodejs
    state: present

