---
# roles/nginx/tasks/main.yml

- name: Install required Python packages for Ansible AWS modules
  pip:
    name:
      - boto
      - boto3
    state: present

- name: Ensure nginx group exists
  ansible.builtin.group:
    name: nginx
    state: present
  become: true

- name: Ensure sockets directory exists
  ansible.builtin.file:
    path: /home/ec2-user/raisetech-live8-sample-app/tmp/sockets
    state: directory
    owner: ec2-user
    group: nginx
    mode: '0775'

- name: Check if Puma socket exists
  ansible.builtin.stat:
    path: /home/ec2-user/raisetech-live8-sample-app/tmp/sockets/puma.sock
  register: puma_socket_stat

- name: Set permissions for Puma socket if it exists
  ansible.builtin.file:
    path: /home/ec2-user/raisetech-live8-sample-app/tmp/sockets/puma.sock
    owner: ec2-user
    group: nginx
    mode: '0775'
  when: puma_socket_stat.stat.exists

- name: Install Nginx
  ansible.builtin.shell:
    cmd: amazon-linux-extras install nginx1 -y
  become: true

# - name: Create directory for app configuration files
#   ansible.builtin.file:
#     path: /etc/nginx/conf.d/rails.conf
#     state: directory
#     mode: '0755'
#   become: true

# - name: Create Nginx configuration for Rails app
#   ansible.builtin.template:
#     src: rails.conf.j2
#     dest: /etc/nginx/conf.d/rails.conf
#     mode: '0644'
#   become: true

- name: Copy nginx general configuration file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  become: true

- name: Test Nginx configuration
  ansible.builtin.command: nginx -t
  register: nginx_test
  ignore_errors: true

- name: Reload Nginx after updating configuration
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true
  when: nginx_test.rc == 0

- name: Enable Nginx to start on boot
  ansible.builtin.service:
    name: nginx
    enabled: yes
  become: true
