plugin: aws_ec2  # EC2インベントリプラグイン
regions:
  - ap-northeast-1  # 使用しているAWSリージョンを指定（例: 東京リージョン）
filters:
  instance-state-name: running  # 実行中のインスタンスのみを対象
  tag:Name: lec13  # インスタンスに設定したタグを指定（例: Nameタグに"lec13"がついたインスタンス）

hostnames:
  - tag:Name  # インスタンスの名前をホスト名として使用

compose:
  ansible_host: public_ip_address  # ansible_host にインスタンスのパブリックIPアドレスを指定

auth:
  aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"  # 環境変数からアクセスキーを取得
  aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"  # 環境変数からシークレットキーを取得
