---
- name: Setup and deploy Rails application
  hosts: all
  become: true

  vars_files:
    - vars/main.yml

  roles:
    - git
    - ruby-bundler
    - rails
    - nodejs
    - yarn
    - bin_setup
    - mysql
    - puma
    - nginx
