---
- name: Setup and deploy Rails application
  hosts: lec13
  become: true
  gather_facts: false

  vars_files:
    - vars/main.yml

  roles:
    - git
    - ruby-bundler
    - rails
    - nodejs
    - yarn
    - mysql
    - bin_setup
    - puma
    - nginx
